### ISSUE TITLE
Requirements conflict

### ISSUE THREAD

**Issue by johnosn** [CiscoSecurity/tr-05-serverless-pulsedive#56]
The [requirements.txt file for this repository](https://github.com/CiscoSecurity/tr-05-serverless-pulsedive/blob/develop/requirements.txt) specifies

> Authlib==0.15.2
> git+https://github.com/CiscoSecurity/tr-05-jwt-generator.git

The [requirements.txt file for tr-05-jwt-generator](https://github.com/CiscoSecurity/tr-05-jwt-generator/blob/develop/requirements.txt) specifies
 
> Authlib==0.14.3

Because Authlib is specified for both using "==" for different versions there is a conflict when putting in the same python virtual environment.

**Comment by AnastasiiaRozlyvan** [comment]
Thank you very much @johnosn for your feedback! Nice catch. We will fix this issue in the next PR.
